volumes:
  bundle:
    driver: local

services:
  web:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - 80:80
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
